package entity;

public enum FacilityType {
    FOOTBALL_11V11,
    FOOTBALL_7V7,
    FOOTBALL_5V5,
    BASKETBALL_INDOOR,
    BASKETBALL_OUTDOOR,
    VOLLEYBALL_INDOOR,
    VOLLEYBALL_OUTDOOR,
    TENNIS_CLAY,
    TENNIS_GRASS,
    TENNIS_HARD,
    PADEL_SINGLE,
    PADEL_DOUBLE,
    BOWLING_ALLEY,
    POOL_TABLE
}
